name: doc
on:
  push:
    branches:
      - main

jobs:
  deploy_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: "3.10"

    - uses: extractions/setup-just@v1

    - name: Install poetry
      run: |
        python -m pip install poetry

    - name: Prepare project for development
      run: |
        just setup

    - name: Build documentation
      run: |
         just build-doc

    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        token: ${{ secrets.GH_PAT }}
        branch: gh-pages
        folder: site
